import nodemailer from "nodemailer";

function isLikelyLocalSmtpHost(host: string): boolean {
  const h = String(host || "").trim().toLowerCase();
  return h === "localhost" || h === "127.0.0.1" || h === "mailhog" || h === "mailpit";
}

function createTransporter() {
  const host = process.env.SMTP_HOST || "smtp.gmail.com";
  const port = parseInt(process.env.SMTP_PORT || "587", 10);
  const user = String(process.env.SMTP_USER || "").trim();
  const pass = String(process.env.SMTP_PASS || "").trim();
  const hasAuth = !!user && !!pass;

  return nodemailer.createTransport({
    host,
    port,
    secure: false,
    ...(hasAuth ? { auth: { user, pass } } : {}),
  });
}

export interface EmailPayload {
  to: string[];
  subject: string;
  html: string;
  text: string;
}

export async function sendEmail(payload: EmailPayload): Promise<boolean> {
  const host = process.env.SMTP_HOST || "smtp.gmail.com";
  const user = String(process.env.SMTP_USER || "").trim();
  const pass = String(process.env.SMTP_PASS || "").trim();
  const hasAuth = !!user && !!pass;

  if (!hasAuth && !isLikelyLocalSmtpHost(host)) {
    console.warn("SMTP not configured - email not sent. Set SMTP_USER and SMTP_PASS, or use local SMTP host (localhost/mailhog/mailpit).");
    return false;
  }

  const transporter = createTransporter();

  try {
    await transporter.sendMail({
      from: process.env.SMTP_FROM || process.env.SMTP_USER,
      to: payload.to.join(", "),
      subject: payload.subject,
      html: payload.html,
      text: payload.text,
    });
    return true;
  } catch (err) {
    console.warn("SMTP send failed - email not sent:", err);
    return false;
  }
}

export function formatGroomingSummaryHTML(data: {
  storyTitle: string;
  storyUrl: string;
  scenarios: { name: string; given: string; when: string; then: string }[];
  acceptanceCriteria: string[];
  testCases: { name: string; description: string }[];
  subtasks: { title: string; estimate?: string }[];
  spikes: string[];
}): string {
  return `
    <div style="font-family: -apple-system, sans-serif; max-width: 700px; margin: 0 auto;">
      <h1 style="color: #1a1a1a; border-bottom: 2px solid #0969da; padding-bottom: 8px;">
        🧹 Grooming Summary
      </h1>
      <h2><a href="${escapeHtml(data.storyUrl)}" style="color: #0969da;">${escapeHtml(data.storyTitle)}</a></h2>

      <h3 style="color: #24292f;">📋 Scenarios</h3>
      <table style="width: 100%; border-collapse: collapse; margin-bottom: 16px;">
        <tr style="background: #f6f8fa;">
          <th style="padding: 8px; border: 1px solid #d1d9e0; text-align: left;">Scenario</th>
          <th style="padding: 8px; border: 1px solid #d1d9e0; text-align: left;">Given</th>
          <th style="padding: 8px; border: 1px solid #d1d9e0; text-align: left;">When</th>
          <th style="padding: 8px; border: 1px solid #d1d9e0; text-align: left;">Then</th>
        </tr>
        ${data.scenarios.map((s) => `
          <tr>
            <td style="padding: 8px; border: 1px solid #d1d9e0;">${escapeHtml(s.name)}</td>
            <td style="padding: 8px; border: 1px solid #d1d9e0;">${escapeHtml(s.given)}</td>
            <td style="padding: 8px; border: 1px solid #d1d9e0;">${escapeHtml(s.when)}</td>
            <td style="padding: 8px; border: 1px solid #d1d9e0;">${escapeHtml(s.then)}</td>
          </tr>
        `).join("")}
      </table>

      <h3 style="color: #24292f;">✅ Acceptance Criteria</h3>
      <ul>${data.acceptanceCriteria.map((c) => `<li>${escapeHtml(c)}</li>`).join("")}</ul>

      <h3 style="color: #24292f;">🧪 Test Cases</h3>
      <ul>${data.testCases.map((t) => `<li><strong>${escapeHtml(t.name)}</strong>: ${escapeHtml(t.description)}</li>`).join("")}</ul>

      <h3 style="color: #24292f;">📦 Subtasks</h3>
      <ul>${data.subtasks.map((s) => `<li>${escapeHtml(s.title)}${s.estimate ? ` <em>(${escapeHtml(s.estimate)})</em>` : ""}</li>`).join("")}</ul>

      ${data.spikes.length > 0 ? `
        <h3 style="color: #24292f;">⚡ Spikes</h3>
        <ul>${data.spikes.map((s) => `<li>${escapeHtml(s)}</li>`).join("")}</ul>
      ` : ""}

      <hr style="border: 1px solid #d1d9e0; margin-top: 24px;" />
      <p style="color: #656d76; font-size: 12px;">
        Generated by GroomPilot · ${new Date().toISOString().split("T")[0]}
      </p>
    </div>
  `;
}

export function formatPRReviewSummaryHTML(data: {
  prTitle: string;
  prUrl: string;
  verdict: string;
  complianceScore?: number;
  totalFindings: number;
  blockers: number;
  warnings: number;
  riskLabel?: string;
  findings: Array<{
    title: string;
    severity?: string;
    action?: string;
    category?: string;
    dimension?: string;
    file?: string;
    line?: number;
    message?: string;
    suggestedFix?: string;
  }>;
}): string {
  const verdictTone = String(data.verdict || "").toLowerCase();
  const verdictColor = verdictTone === "block"
    ? "#cf222e"
    : verdictTone === "warning"
      ? "#9a6700"
      : "#1a7f37";

  return `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 760px; margin: 0 auto; color: #24292f;">
      <h1 style="margin: 0 0 12px;">Peer Review Summary</h1>
      <p style="margin: 0 0 16px;">
        <a href="${escapeHtml(data.prUrl || "#")}" style="color: #0969da; text-decoration: none;">${escapeHtml(data.prTitle || "Pull Request")}</a>
      </p>

      <div style="border: 1px solid #d0d7de; border-radius: 8px; padding: 12px; margin-bottom: 16px;">
        <div style="display: inline-block; background: ${verdictColor}; color: #fff; padding: 4px 10px; border-radius: 999px; font-size: 12px; font-weight: 700; letter-spacing: .4px;">
          VERDICT: ${escapeHtml(String(data.verdict || "unknown").toUpperCase())}
        </div>
        <table style="width: 100%; border-collapse: collapse; margin-top: 10px;">
          <tr>
            <td style="padding: 6px 0; font-size: 13px;"><strong>Compliance Score</strong></td>
            <td style="padding: 6px 0; font-size: 13px; text-align: right;">${typeof data.complianceScore === "number" ? `${data.complianceScore}%` : "n/a"}</td>
          </tr>
          <tr>
            <td style="padding: 6px 0; font-size: 13px;"><strong>Total Findings</strong></td>
            <td style="padding: 6px 0; font-size: 13px; text-align: right;">${data.totalFindings}</td>
          </tr>
          <tr>
            <td style="padding: 6px 0; font-size: 13px;"><strong>Blockers</strong></td>
            <td style="padding: 6px 0; font-size: 13px; text-align: right;">${data.blockers}</td>
          </tr>
          <tr>
            <td style="padding: 6px 0; font-size: 13px;"><strong>Warnings</strong></td>
            <td style="padding: 6px 0; font-size: 13px; text-align: right;">${data.warnings}</td>
          </tr>
          <tr>
            <td style="padding: 6px 0; font-size: 13px;"><strong>Risk Label</strong></td>
            <td style="padding: 6px 0; font-size: 13px; text-align: right;">${escapeHtml(data.riskLabel || "n/a")}</td>
          </tr>
        </table>
      </div>

      <h2 style="margin: 0 0 10px; font-size: 18px;">Findings</h2>
      ${data.findings.length === 0 ? "<p style='font-size: 14px;'>No material issues detected.</p>" : `
        <ol style="padding-left: 20px; margin: 0;">
          ${data.findings.slice(0, 20).map((f) => `
            <li style="margin-bottom: 12px;">
              <div style="font-size: 14px;"><strong>${escapeHtml(f.title || "Untitled finding")}</strong></div>
              <div style="font-size: 12px; color: #57606a; margin: 4px 0;">
                ${escapeHtml(String(f.severity || "unknown").toUpperCase())}
                · ${escapeHtml(String(f.action || "unknown"))}
                · ${escapeHtml(f.dimension || "n/a")}
                · ${escapeHtml(f.category || "n/a")}
              </div>
              <div style="font-size: 12px; color: #57606a;">
                ${escapeHtml(f.file || "unknown file")}${typeof f.line === "number" ? `:${f.line}` : ""}
              </div>
              ${f.message ? `<div style="font-size: 13px; margin-top: 4px;">${escapeHtml(f.message)}</div>` : ""}
              ${f.suggestedFix ? `<div style="font-size: 13px; margin-top: 4px;"><strong>Suggested fix:</strong> ${escapeHtml(f.suggestedFix)}</div>` : ""}
            </li>
          `).join("")}
        </ol>
      `}

      <hr style="border: 1px solid #d0d7de; margin: 18px 0 12px;" />
      <p style="color: #656d76; font-size: 12px; margin: 0;">
        Generated by GroomPilot · ${new Date().toISOString().split("T")[0]}
      </p>
    </div>
  `;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
