import crypto from "crypto";
import { complete, isAIEnabled, getProviderInfo } from "./ai-provider";
import {
  browseRepo, getFileContent, BBFileEntry,
} from "./bitbucket-server";
import {
  startIndexRun, completeIndexRun, failIndexRun,
  upsertCodeFiles, clearFileIndex, insertSymbols, insertDependencies,
  insertAnnotations, insertGuards, upsertAISummaries, upsertBaselineVulns,
  getCodeFile, clearRepoIndex,
  type UpsertCodeFileInput, type InsertSymbolInput, type InsertDependencyInput,
  type InsertAnnotationInput, type InsertGuardInput, type UpsertAISummaryInput,
  type UpsertBaselineVulnInput,
} from "./repo-code-index-store";
import {
  clearFileGraph,
  clearRepoGraph,
  upsertGraphNodes,
  upsertGraphEdges,
  type GraphNodeInput,
  type GraphEdgeInput,
} from "./repo-code-graph-store";

// ─── Configuration ─────────────────────────────────────────────────────────────

const TARGET_EXTENSIONS = new Set([
  ".java", ".groovy",
  ".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx",
  ".ts", ".tsx", ".js", ".jsx",
  ".py",
]);

const MAX_FILE_LINES = 5000;
const MAX_AI_SUMMARY_FILES = 40;
const MAX_BROWSE_DEPTH = 6;

// ─── Language detection ────────────────────────────────────────────────────────

function detectLanguage(filePath: string): string | null {
  const lower = filePath.toLowerCase();
  const ext = lower.slice(lower.lastIndexOf("."));
  if (!TARGET_EXTENSIONS.has(ext)) return null;
  if (ext === ".java") return "java";
  if (ext === ".groovy") return "groovy";
  if (ext === ".py") return "python";
  if ([".ts", ".tsx"].includes(ext)) return "typescript";
  if ([".js", ".jsx"].includes(ext)) return "javascript";
  if ([".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx"].includes(ext)) return "c/c++";
  return null;
}

// ─── Classification helpers (mirrored from pr-review.ts) ───────────────────────

function isTestFilePath(file: string): boolean {
  const lower = file.toLowerCase();
  return (
    lower.includes("/src/test/") ||
    lower.includes("/tests/") ||
    lower.includes("/test/") ||
    /(test|spec|it)\.[a-z0-9]+$/.test(lower)
  );
}

function classifySubsystem(file: string): string {
  const path = file.toLowerCase();
  if (/auth|security|jwt|oauth|login|token/.test(path)) return "auth";
  if (/payment|transaction|ledger|settlement|invoice|refund|billing|reconciliation|groom/.test(path)) return "payments";
  if (/customer|profile|user|email|notification/.test(path)) return "customer";
  if (/db|migration|schema|sql|liquibase|flyway/.test(path)) return "data";
  if (/metrics|prometheus|telemetry|observability|logging/.test(path)) return "observability";
  if (/docker|helm|deploy|infra|k8s|terraform|jenkins|workflow/.test(path)) return "platform";
  if (/api|route|controller|openapi|swagger/.test(path)) return "api";
  if (/frontend|component|tsx$|jsx$|css$/.test(path)) return "frontend";
  if (/test|spec/.test(path)) return "test";
  return "core";
}

function detectSensitivity(filePath: string, content: string): string[] {
  const path = filePath.toLowerCase();
  const text = content.toLowerCase();
  const sensitivity: string[] = [];
  if (/auth|security|jwt|oauth|token|login|rbac|permission/.test(path) || /authorize|permission|role|token|jwt/.test(text)) sensitivity.push("auth");
  if (/payment|transaction|refund|ledger|settle|reconcil|money|balance/.test(path) || /transfer|charge|debit|credit|balance/.test(text)) sensitivity.push("money-movement");
  if (/pii|customer|email|profile|user|personal|ssn|pan|card/.test(path) || /email|ssn|pan|customer|personal/.test(text)) sensitivity.push("pii");
  if (/crypto|encrypt|decrypt|cipher|signature|hash/.test(path) || /messagedigest|cipher|getinstance|sha1|md5|des|rsa/.test(text)) sensitivity.push("crypto");
  if (/migration|schema|sql|flyway|liquibase/.test(path)) sensitivity.push("migrations");
  return sensitivity;
}

function isGeneratedFile(filePath: string, content: string): boolean {
  const name = filePath.toLowerCase();
  const text = content.toLowerCase().slice(0, 2000);
  return (
    /(^|\/)(dist|build|coverage|generated|gen)\//.test(name) ||
    /\.generated\.(ts|js|java|py|cs)$/.test(name) ||
    /(_pb2\.py|\.pb\.java|\.g\.java|\.designer\.cs|\.min\.js|\.map)$/.test(name) ||
    /generated by|auto-generated|autogenerated|do not edit|codegen/.test(text)
  );
}

/** Returns true for Spring / config files that define bean wiring */
function isConfigFile(filePath: string): boolean {
  const lower = filePath.toLowerCase();
  return (
    lower.endsWith(".properties") || lower.endsWith(".yml") || lower.endsWith(".yaml") ||
    lower.endsWith(".xml")
  );
}

/**
 * Extract bean-wiring dependencies from Spring/config property files.
 * Detects datasource URLs, class references, and spring.profiles.
 */
function extractConfigDependencies(content: string, filePath: string): ExtractedDependency[] {
  const deps: ExtractedDependency[] = [];
  const lower = filePath.toLowerCase();

  if (lower.endsWith(".properties") || lower.endsWith(".yml") || lower.endsWith(".yaml")) {
    // Detect fully-qualified class references (e.g. spring.datasource.driver-class-name, spring.jpa.hibernate.ddl-auto)
    const fqcnPattern = /=\s*([a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*){2,}(?:\.[A-Z]\w*))/g;
    let match: RegExpExecArray | null;
    while ((match = fqcnPattern.exec(content)) !== null) {
      deps.push({ targetSymbol: match[1], dependencyType: "config-class-ref", metadata: { configFile: filePath } });
    }
    // Detect datasource / messaging URLs
    const urlPattern = /(?:url|uri|endpoint|host)\s*[=:]\s*([^\s#]+)/gi;
    while ((match = urlPattern.exec(content)) !== null) {
      deps.push({ targetSymbol: match[1].slice(0, 120), dependencyType: "config-resource", metadata: { configFile: filePath } });
    }
    // Bean overrides: class: or type: references
    const beanClassPattern = /(?:class|type)\s*:\s*([a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*)*\.[A-Z]\w*)/g;
    while ((match = beanClassPattern.exec(content)) !== null) {
      deps.push({ targetSymbol: match[1], dependencyType: "config-bean-ref", metadata: { configFile: filePath } });
    }
  }

  if (lower.endsWith(".xml")) {
    // Spring XML bean definitions: <bean class="com.example.MyBean"> or ref="beanName"
    const xmlBeanPattern = /class\s*=\s*"([a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*)*\.[A-Z]\w*)"/g;
    let match: RegExpExecArray | null;
    while ((match = xmlBeanPattern.exec(content)) !== null) {
      deps.push({ targetSymbol: match[1], dependencyType: "config-bean-ref", metadata: { configFile: filePath } });
    }
    const xmlRefPattern = /ref\s*=\s*"([^"]+)"/g;
    while ((match = xmlRefPattern.exec(content)) !== null) {
      deps.push({ targetSymbol: match[1], dependencyType: "config-bean-ref", metadata: { configFile: filePath } });
    }
  }

  return deps;
}

function isInfraConfig(filePath: string): boolean {
  const name = filePath.toLowerCase();
  return /(^|\/)(dockerfile|docker-compose|helm|charts|terraform|k8s|kubernetes|deploy|deployment|jenkins|github\/workflows|cloudformation|ansible|pulumi|infra|config)\b/.test(name)
    || /\.(ya?ml|json|toml|ini|properties|conf|env)$/.test(name);
}

function detectMicroserviceName(filePath: string, repoSlug: string): string {
  const normalized = filePath.replace(/^\/+/, "");
  const parts = normalized.split("/").filter(Boolean);
  if (parts.length === 0) return repoSlug;
  const first = parts[0].toLowerCase();
  if (["src", "lib", "app", "test", "tests", "config"].includes(first)) return repoSlug;
  return parts[0];
}

function buildMethodBody(content: string, lineStart?: number, lineEnd?: number): string | undefined {
  if (!lineStart || !lineEnd || lineStart < 1 || lineEnd < lineStart) return undefined;
  const lines = content.split("\n");
  const body = lines.slice(lineStart - 1, Math.min(lineEnd, lines.length)).join("\n");
  return body.length > 12000 ? body.slice(0, 12000) : body;
}

function buildGraphWarehouseForFile(params: {
  repoSlug: string;
  filePath: string;
  content: string;
  symbols: ExtractedSymbol[];
  dependencies: ExtractedDependency[];
  annotations: ExtractedAnnotation[];
  subsystem: string;
}): { nodes: GraphNodeInput[]; edges: GraphEdgeInput[] } {
  const { repoSlug, filePath, content, symbols, dependencies, annotations, subsystem } = params;

  const nodes: GraphNodeInput[] = [];
  const edges: GraphEdgeInput[] = [];
  const nodeSeen = new Set<string>();
  const edgeSeen = new Set<string>();
  const symbolToNode = new Map<string, string>();

  const sourceMicroservice = detectMicroserviceName(filePath, repoSlug);
  const fileNodeKey = `file:${filePath}`;
  const microserviceNodeKey = `microservice:${sourceMicroservice}`;

  const pushNode = (node: GraphNodeInput) => {
    const key = `${node.nodeType}:${node.nodeKey}`;
    if (nodeSeen.has(key)) return;
    nodeSeen.add(key);
    nodes.push(node);
  };

  const pushEdge = (edge: GraphEdgeInput) => {
    const key = `${edge.fromNodeKey}->${edge.toNodeKey}:${edge.edgeType}`;
    if (edgeSeen.has(key)) return;
    edgeSeen.add(key);
    edges.push(edge);
  };

  pushNode({
    nodeKey: fileNodeKey,
    nodeType: "File",
    filePath,
    microservice: sourceMicroservice,
    metadata: { subsystem },
  });

  pushNode({
    nodeKey: microserviceNodeKey,
    nodeType: "Microservice",
    microservice: sourceMicroservice,
  });

  pushEdge({ fromNodeKey: fileNodeKey, toNodeKey: microserviceNodeKey, edgeType: "MICROSERVICE_LINK" });

  for (const symbol of symbols) {
    const symbolNodeKey = `symbol:${filePath}:${symbol.name}:${symbol.lineStart || 0}`;
    symbolToNode.set(symbol.name, symbolNodeKey);

    const symbolType: GraphNodeInput["nodeType"] =
      symbol.type === "class" || symbol.type === "interface" || symbol.type === "enum" || symbol.type === "struct"
        ? "Class"
        : "Method";

    const symbolAnnotations = annotations
      .filter((a) => a.targetSymbol === symbol.name)
      .map((a) => a.annotationName);

    pushNode({
      nodeKey: symbolNodeKey,
      nodeType: symbolType,
      filePath,
      symbolName: symbol.name,
      microservice: sourceMicroservice,
      signature: symbol.signature,
      visibility: symbol.visibility,
      returnType: symbol.returnType,
      lineStart: symbol.lineStart,
      lineEnd: symbol.lineEnd,
      methodBody: symbolType === "Method" ? buildMethodBody(content, symbol.lineStart, symbol.lineEnd) : undefined,
      annotations: symbolAnnotations,
      metadata: { parentSymbol: symbol.parentSymbol || null },
    });

    pushEdge({ fromNodeKey: fileNodeKey, toNodeKey: symbolNodeKey, edgeType: "USES" });
  }

  for (const annotation of annotations) {
    const annotationNodeKey = `annotation:${annotation.annotationName.toLowerCase()}`;
    pushNode({
      nodeKey: annotationNodeKey,
      nodeType: "Annotation",
      filePath,
      symbolName: annotation.annotationName,
      metadata: {
        classification: annotation.classification,
        lineNumber: annotation.lineNumber,
      },
    });

    const targetKey = symbolToNode.get(annotation.targetSymbol);
    if (targetKey) {
      pushEdge({ fromNodeKey: targetKey, toNodeKey: annotationNodeKey, edgeType: "HAS_ANNOTATION" });
    }
  }

  for (const dep of dependencies) {
    const sourceNodeKey = dep.sourceSymbol && symbolToNode.get(dep.sourceSymbol)
      ? symbolToNode.get(dep.sourceSymbol)!
      : fileNodeKey;

    let targetNodeKey: string;
    if (dep.targetFile) {
      targetNodeKey = `file:${dep.targetFile}`;
      pushNode({
        nodeKey: targetNodeKey,
        nodeType: "File",
        filePath: dep.targetFile,
        microservice: detectMicroserviceName(dep.targetFile, repoSlug),
      });
    } else if (dep.targetSymbol) {
      const existing = symbolToNode.get(dep.targetSymbol);
      if (existing) {
        targetNodeKey = existing;
      } else {
        const guessedType: GraphNodeInput["nodeType"] =
          ["extends", "implements", "injection"].includes(dep.dependencyType)
            ? "Class"
            : "Method";
        targetNodeKey = `external:${dep.targetSymbol}`;
        pushNode({
          nodeKey: targetNodeKey,
          nodeType: guessedType,
          symbolName: dep.targetSymbol,
        });
      }
    } else {
      continue;
    }

    pushEdge({
      fromNodeKey: sourceNodeKey,
      toNodeKey: targetNodeKey,
      edgeType: dep.dependencyType === "method-call" ? "CALLS" : "USES",
      metadata: { dependencyType: dep.dependencyType },
    });

    if (dep.targetFile) {
      const targetMicroservice = detectMicroserviceName(dep.targetFile, repoSlug);
      if (targetMicroservice && targetMicroservice !== sourceMicroservice) {
        const targetServiceNodeKey = `microservice:${targetMicroservice}`;
        pushNode({
          nodeKey: targetServiceNodeKey,
          nodeType: "Microservice",
          microservice: targetMicroservice,
        });
        pushEdge({
          fromNodeKey: microserviceNodeKey,
          toNodeKey: targetServiceNodeKey,
          edgeType: "DEPENDS_ON_SERVICE",
        });
      }
    }
  }

  return { nodes, edges };
}

// ─── Symbol extraction ─────────────────────────────────────────────────────────

interface ExtractedSymbol {
  name: string;
  type: "class" | "interface" | "enum" | "function" | "method" | "constant" | "struct";
  visibility?: string;
  isStatic: boolean;
  isAbstract: boolean;
  lineStart: number;
  lineEnd: number;
  parentSymbol?: string;
  signature?: string;
  returnType?: string;
  parameterTypes?: string;
}

function extractSymbols(content: string, language: string, filePath: string): ExtractedSymbol[] {
  const lines = content.split("\n");
  const symbols: ExtractedSymbol[] = [];

  if (language === "java" || language === "groovy") {
    extractJavaSymbols(lines, symbols);
  } else if (language === "typescript" || language === "javascript") {
    extractTsSymbols(lines, symbols);
  } else if (language === "python") {
    extractPythonSymbols(lines, symbols);
  } else if (language === "c/c++") {
    extractCppSymbols(lines, symbols);
  }

  // Compute line end via brace/indent tracking (simplified)
  for (let i = 0; i < symbols.length; i++) {
    const nextStart = symbols[i + 1]?.lineStart ?? lines.length + 1;
    if (symbols[i].lineEnd <= symbols[i].lineStart) {
      symbols[i].lineEnd = nextStart - 1;
    }
  }

  return symbols;
}

function extractJavaSymbols(lines: string[], symbols: ExtractedSymbol[]): void {
  const classPattern = /^\s*(public|private|protected|abstract|final|static)?\s*(class|interface|enum)\s+([A-Za-z_]\w*)/;
  const methodPattern = /^\s*(public|private|protected|static|final|abstract|synchronized|\s)*\s*(<[^>]+>\s+)?([A-Za-z_]\w*(?:<[^>]*>)?(?:\[\])?)\s+([A-Za-z_]\w*)\s*\(([^)]*)\)/;
  let currentClass: string | undefined;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const classMatch = line.match(classPattern);
    if (classMatch) {
      currentClass = classMatch[3];
      symbols.push({
        name: currentClass,
        type: classMatch[2] as "class" | "interface" | "enum",
        visibility: classMatch[1] || "package-private",
        isStatic: line.includes("static"),
        isAbstract: line.includes("abstract"),
        lineStart: i + 1,
        lineEnd: i + 1,
        signature: line.trim(),
      });
      continue;
    }
    const methodMatch = line.match(methodPattern);
    if (methodMatch && !line.trim().startsWith("//") && !line.trim().startsWith("*")) {
      const visibility = /public|private|protected/.exec(line)?.[0] || "package-private";
      symbols.push({
        name: methodMatch[4],
        type: "method",
        visibility,
        isStatic: line.includes("static"),
        isAbstract: line.includes("abstract"),
        lineStart: i + 1,
        lineEnd: i + 1,
        parentSymbol: currentClass,
        signature: line.trim(),
        returnType: methodMatch[3],
        parameterTypes: methodMatch[5]?.trim() || undefined,
      });
    }
  }
}

function extractTsSymbols(lines: string[], symbols: ExtractedSymbol[]): void {
  const classPattern = /^\s*(export\s+)?(abstract\s+)?class\s+([A-Za-z_]\w*)/;
  const funcPattern = /^\s*(export\s+)?(async\s+)?function\s+([A-Za-z_]\w*)/;
  const constPattern = /^\s*(export\s+)?const\s+([A-Za-z_]\w*)\s*=\s*(async\s+)?\(/;
  const methodPattern = /^\s*(public|private|protected|static|async|\s)*\s*([A-Za-z_]\w*)\s*\(([^)]*)\)\s*[:{]/;

  let currentClass: string | undefined;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const classMatch = line.match(classPattern);
    if (classMatch) {
      currentClass = classMatch[3];
      symbols.push({
        name: currentClass,
        type: "class",
        visibility: line.includes("export") ? "public" : "private",
        isStatic: false,
        isAbstract: line.includes("abstract"),
        lineStart: i + 1,
        lineEnd: i + 1,
        signature: line.trim(),
      });
      continue;
    }
    const funcMatch = line.match(funcPattern);
    if (funcMatch) {
      symbols.push({
        name: funcMatch[3],
        type: "function",
        visibility: line.includes("export") ? "public" : "private",
        isStatic: false,
        isAbstract: false,
        lineStart: i + 1,
        lineEnd: i + 1,
        signature: line.trim(),
      });
      continue;
    }
    const constMatch = line.match(constPattern);
    if (constMatch) {
      symbols.push({
        name: constMatch[2],
        type: "function",
        visibility: line.includes("export") ? "public" : "private",
        isStatic: false,
        isAbstract: false,
        lineStart: i + 1,
        lineEnd: i + 1,
        signature: line.trim(),
      });
      continue;
    }
    if (currentClass) {
      const methodMatch = line.match(methodPattern);
      if (methodMatch && !line.trim().startsWith("//") && !line.trim().startsWith("*")) {
        symbols.push({
          name: methodMatch[2],
          type: "method",
          visibility: /public|private|protected/.exec(line)?.[0] || "public",
          isStatic: line.includes("static"),
          isAbstract: false,
          lineStart: i + 1,
          lineEnd: i + 1,
          parentSymbol: currentClass,
          signature: line.trim(),
          parameterTypes: methodMatch[3]?.trim() || undefined,
        });
      }
    }
  }
}

function extractPythonSymbols(lines: string[], symbols: ExtractedSymbol[]): void {
  const classPattern = /^class\s+([A-Za-z_]\w*)\s*[:(]/;
  const funcPattern = /^(\s*)(async\s+)?def\s+([A-Za-z_]\w*)\s*\(([^)]*)\)/;
  let currentClass: string | undefined;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const classMatch = line.match(classPattern);
    if (classMatch) {
      currentClass = classMatch[1];
      symbols.push({
        name: currentClass,
        type: "class",
        visibility: currentClass.startsWith("_") ? "private" : "public",
        isStatic: false,
        isAbstract: false,
        lineStart: i + 1,
        lineEnd: i + 1,
        signature: line.trim(),
      });
      continue;
    }
    const funcMatch = line.match(funcPattern);
    if (funcMatch) {
      const indent = funcMatch[1].length;
      const name = funcMatch[3];
      const isMethod = indent > 0 && currentClass;
      symbols.push({
        name,
        type: isMethod ? "method" : "function",
        visibility: name.startsWith("_") ? "private" : "public",
        isStatic: false,
        isAbstract: false,
        lineStart: i + 1,
        lineEnd: i + 1,
        parentSymbol: isMethod ? currentClass : undefined,
        signature: line.trim(),
        parameterTypes: funcMatch[4]?.trim() || undefined,
      });
    }
  }
}

function extractCppSymbols(lines: string[], symbols: ExtractedSymbol[]): void {
  const classPattern = /^\s*(class|struct)\s+([A-Za-z_]\w*)/;
  const funcPattern = /^\s*(static\s+|inline\s+|constexpr\s+|virtual\s+)?([A-Za-z_][\w:<>~*&]*)\s+([A-Za-z_]\w*)\s*\(([^)]*)\)/;
  let currentClass: string | undefined;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const classMatch = line.match(classPattern);
    if (classMatch) {
      currentClass = classMatch[2];
      symbols.push({
        name: currentClass,
        type: classMatch[1] === "struct" ? "struct" : "class",
        visibility: "public",
        isStatic: false,
        isAbstract: false,
        lineStart: i + 1,
        lineEnd: i + 1,
        signature: line.trim(),
      });
      continue;
    }
    const funcMatch = line.match(funcPattern);
    if (funcMatch && !line.trim().startsWith("//") && !line.trim().startsWith("*") && !line.trim().startsWith("#")) {
      symbols.push({
        name: funcMatch[3],
        type: currentClass ? "method" : "function",
        visibility: "public",
        isStatic: line.includes("static"),
        isAbstract: line.includes("virtual") && line.includes("= 0"),
        lineStart: i + 1,
        lineEnd: i + 1,
        parentSymbol: currentClass,
        signature: line.trim(),
        returnType: funcMatch[2],
        parameterTypes: funcMatch[4]?.trim() || undefined,
      });
    }
  }
}

// ─── Dependency extraction ─────────────────────────────────────────────────────

interface ExtractedDependency {
  sourceSymbol?: string;
  targetFile?: string;
  targetSymbol?: string;
  dependencyType: string;
  metadata?: Record<string, unknown>;
}

function extractDependencies(content: string, language: string, filePath: string): ExtractedDependency[] {
  const deps: ExtractedDependency[] = [];

  if (language === "java" || language === "groovy") {
    // Import dependencies
    const importPattern = /^import\s+(?:static\s+)?([a-zA-Z_][\w.]*);/gm;
    let match: RegExpExecArray | null;
    while ((match = importPattern.exec(content)) !== null) {
      const fqn = match[1];
      const isStatic = match[0].includes("static");
      deps.push({
        targetSymbol: fqn,
        dependencyType: isStatic ? "static-import" : "import",
      });
    }
    // Inheritance
    const extendsPattern = /class\s+\w+\s+extends\s+([A-Za-z_]\w*)/g;
    while ((match = extendsPattern.exec(content)) !== null) {
      deps.push({ targetSymbol: match[1], dependencyType: "extends" });
    }
    const implPattern = /class\s+\w+.*?implements\s+([A-Za-z_][\w,\s<>]*)/g;
    while ((match = implPattern.exec(content)) !== null) {
      const impls = match[1].split(",").map((s) => s.trim().replace(/<.*>/, ""));
      for (const impl of impls) {
        if (impl) deps.push({ targetSymbol: impl, dependencyType: "implements" });
      }
    }
    // Spring injection
    const injectPattern = /@(?:Autowired|Inject|Resource)\s+(?:private\s+)?([A-Za-z_]\w*)\s+(\w+)/g;
    while ((match = injectPattern.exec(content)) !== null) {
      deps.push({ targetSymbol: match[1], dependencyType: "injection" });
    }
    // Method calls to other services (heuristic: camelCase field calls)
    const callPattern = /(?:this\.)?([a-z]\w*(?:Service|Repository|Dao|Client|Handler|Manager))\.\w+\(/g;
    while ((match = callPattern.exec(content)) !== null) {
      deps.push({ targetSymbol: match[1], dependencyType: "method-call" });
    }
    // AOP cross-cutting: @Around / @Before / @After with pointcut targeting other classes
    const aopPattern = /@(?:Around|Before|After|AfterReturning|AfterThrowing)\s*\(\s*["']([^"']+)["']/g;
    while ((match = aopPattern.exec(content)) !== null) {
      const pointcut = match[1];
      // Extract target class/method from pointcut expressions like "execution(* com.example.MyService.*(..))" 
      const targetMatch = pointcut.match(/execution\([^)]*?([A-Z]\w+)\./);
      deps.push({
        targetSymbol: targetMatch ? targetMatch[1] : pointcut.slice(0, 80),
        dependencyType: "aop-advice",
        metadata: { pointcut },
      });
    }
    // Lombok @RequiredArgsConstructor implicit injection (final fields become constructor-injected)
    if (/@RequiredArgsConstructor/i.test(content)) {
      const finalFieldPattern = /private\s+final\s+([A-Z]\w+)\s+(\w+)\s*;/g;
      while ((match = finalFieldPattern.exec(content)) !== null) {
        deps.push({ targetSymbol: match[1], dependencyType: "injection", metadata: { via: "lombok-constructor" } });
      }
    }
  } else if (language === "typescript" || language === "javascript") {
    const tsImportPattern = /import\s+(?:{([^}]+)}|(\w+))\s+from\s+['"]([^'"]+)['"]/g;
    let match: RegExpExecArray | null;
    while ((match = tsImportPattern.exec(content)) !== null) {
      const specifiers = match[1] || match[2] || "";
      const source = match[3];
      deps.push({
        targetFile: source,
        targetSymbol: specifiers.trim(),
        dependencyType: source.startsWith(".") ? "local-import" : "package-import",
      });
    }
    // require() calls
    const requirePattern = /require\(\s*['"]([^'"]+)['"]\s*\)/g;
    while ((match = requirePattern.exec(content)) !== null) {
      deps.push({
        targetFile: match[1],
        dependencyType: match[1].startsWith(".") ? "local-import" : "package-import",
      });
    }
  } else if (language === "python") {
    const pyImportPattern = /^(?:from\s+(\S+)\s+)?import\s+(.+)/gm;
    let match: RegExpExecArray | null;
    while ((match = pyImportPattern.exec(content)) !== null) {
      const module = match[1] || match[2].split(",")[0].trim();
      deps.push({
        targetSymbol: module,
        targetFile: match[1] || undefined,
        dependencyType: module.startsWith(".") ? "relative-import" : "import",
      });
    }
    // Inheritance
    const pyClassPattern = /class\s+\w+\(([^)]+)\)/g;
    while ((match = pyClassPattern.exec(content)) !== null) {
      const bases = match[1].split(",").map((s) => s.trim());
      for (const base of bases) {
        if (base && base !== "object") {
          deps.push({ targetSymbol: base, dependencyType: "extends" });
        }
      }
    }
  } else if (language === "c/c++") {
    const includePattern = /^#include\s+[<"]([^>"]+)[>"]/gm;
    let match: RegExpExecArray | null;
    while ((match = includePattern.exec(content)) !== null) {
      deps.push({
        targetFile: match[1],
        dependencyType: match[0].includes("<") ? "system-include" : "local-include",
      });
    }
    // Inheritance
    const cppClassPattern = /class\s+\w+\s*:\s*(public|private|protected)\s+([A-Za-z_]\w*)/g;
    while ((match = cppClassPattern.exec(content)) !== null) {
      deps.push({ targetSymbol: match[2], dependencyType: "extends" });
    }
  }

  return deps;
}

// ─── Annotation extraction ─────────────────────────────────────────────────────

interface ExtractedAnnotation {
  targetSymbol: string;
  annotationName: string;
  annotationParams?: string;
  classification: string;
  lineNumber: number;
}

const ANNOTATION_CLASSIFICATIONS: Record<string, string> = {
  // Security
  "@secured": "security", "@rolesallowed": "security", "@preauthorize": "security",
  "@denyall": "security", "@permitall": "security", "@requirespermissions": "security",
  // Validation
  "@valid": "validation", "@validated": "validation",
  "@notnull": "validation", "@nonnull": "validation",
  "@notblank": "validation", "@notempty": "validation",
  "@size": "validation", "@min": "validation", "@max": "validation",
  "@pattern": "validation", "@email": "validation",
  // Transaction
  "@transactional": "transaction",
  // Deprecated
  "@deprecated": "lifecycle", "@suppresswarnings": "lifecycle",
  // Logging / audit
  "@audited": "audit", "@logevent": "audit",
  // Api mapping
  "@getmapping": "api-endpoint", "@postmapping": "api-endpoint",
  "@putmapping": "api-endpoint", "@deletemapping": "api-endpoint",
  "@patchmapping": "api-endpoint", "@requestmapping": "api-endpoint",
  // Test
  "@test": "test", "@beforeeach": "test", "@aftereach": "test",
  "@parameterizedtest": "test", "@springboottest": "test",
  // Configuration
  "@configuration": "config", "@bean": "config",
  "@value": "config", "@configurationproperties": "config",
  // Lombok (code-generation)
  "@data": "lombok", "@builder": "lombok", "@getter": "lombok", "@setter": "lombok",
  "@noargsconstructor": "lombok", "@allargsconstructor": "lombok",
  "@requiredargsconstructor": "lombok", "@tostring": "lombok",
  "@equalsandhashcode": "lombok", "@slf4j": "lombok", "@log": "lombok",
  "@log4j2": "lombok", "@with": "lombok",
  "@superbuilder": "lombok", "@accessors": "lombok",
  // JPA / ORM mapping
  "@entity": "orm", "@table": "orm", "@column": "orm",
  "@id": "orm", "@generatedvalue": "orm",
  "@onetomany": "orm", "@manytoone": "orm",
  "@onetoone": "orm", "@manytomany": "orm",
  "@joincolumn": "orm", "@jointable": "orm",
  "@embeddable": "orm", "@embedded": "orm",
  "@mappedby": "orm", "@enumerated": "orm",
  "@temporal": "orm", "@lob": "orm",
  "@namedquery": "orm", "@query": "orm",
  // AOP (cross-cutting concerns)
  "@aspect": "aop", "@around": "aop", "@before": "aop",
  "@after": "aop", "@afterreturning": "aop", "@afterthrowing": "aop",
  "@pointcut": "aop",
  // Caching
  "@cacheable": "caching", "@cacheevict": "caching", "@cacheput": "caching",
  // Async / scheduling
  "@async": "async", "@enableasync": "async",
  "@enablescheduling": "async", "@scheduled": "lifecycle",
};

function extractAnnotations(content: string, language: string, symbols: ExtractedSymbol[]): ExtractedAnnotation[] {
  if (language !== "java" && language !== "groovy") return [];

  const annotations: ExtractedAnnotation[] = [];
  const lines = content.split("\n");
  const annotationPattern = /^\s*(@[A-Za-z]\w*)(?:\(([^)]*)\))?/;

  for (let i = 0; i < lines.length; i++) {
    const match = lines[i].match(annotationPattern);
    if (!match) continue;

    const annotName = match[1];
    const params = match[2] || undefined;
    const classification = ANNOTATION_CLASSIFICATIONS[annotName.toLowerCase()] || "other";

    // Find nearest following symbol
    let targetSymbol = "module";
    for (const sym of symbols) {
      if (sym.lineStart > i + 1) {
        targetSymbol = sym.name;
        break;
      }
    }

    annotations.push({
      targetSymbol,
      annotationName: annotName,
      annotationParams: params,
      classification,
      lineNumber: i + 1,
    });
  }

  return annotations;
}

// ─── Guard detection ───────────────────────────────────────────────────────────

interface ExtractedGuard {
  protectingSymbol?: string;
  guardType: string;
  scope?: string;
  evidence: string;
  lineNumber: number;
}

function extractGuards(content: string, language: string, symbols: ExtractedSymbol[]): ExtractedGuard[] {
  const guards: ExtractedGuard[] = [];
  const lines = content.split("\n");

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const lower = line.toLowerCase().trim();

    // Find enclosing symbol
    let enclosingSymbol: string | undefined;
    for (const sym of symbols) {
      if (sym.lineStart <= i + 1 && sym.lineEnd >= i + 1) {
        enclosingSymbol = sym.name;
      }
    }

    // Null checks
    if (/!= null|== null|objects\.requirenonnull|optional\.ofnullable|optional\.</i.test(line)) {
      guards.push({ protectingSymbol: enclosingSymbol, guardType: "null-check", evidence: line.trim(), lineNumber: i + 1 });
    }
    // Validation annotations
    if (/^@(nonnull|notnull|valid|validated|notblank|notempty|size|min|max|pattern)/i.test(lower)) {
      guards.push({ protectingSymbol: enclosingSymbol, guardType: "validation-annotation", evidence: line.trim(), lineNumber: i + 1 });
    }
    // Try-catch
    if (/catch\s*\(/.test(line)) {
      guards.push({ protectingSymbol: enclosingSymbol, guardType: "exception-handler", evidence: line.trim(), lineNumber: i + 1 });
    }
    // Parameterized SQL
    if (/preparedstatement|namedparameterjdbctemplate|@query.*:(?!:)/i.test(line)) {
      guards.push({ protectingSymbol: enclosingSymbol, guardType: "parameterized-sql", evidence: line.trim(), lineNumber: i + 1 });
    }
    // Auth guards
    if (/@secured|@preauthorize|@rolesallowed|@denyall/i.test(line)) {
      guards.push({ protectingSymbol: enclosingSymbol, guardType: "auth-guard", evidence: line.trim(), lineNumber: i + 1 });
    }
    // Input sanitization
    if (/escape|sanitize|encode|stripisolatin|htmlutils|owasp/i.test(line)) {
      guards.push({ protectingSymbol: enclosingSymbol, guardType: "input-sanitization", evidence: line.trim(), lineNumber: i + 1 });
    }
    // Bounds check
    if (/(\.length|\.size\(\))\s*(>|>=|<|<=|==|!=)/.test(line) || /index.*bounds|arrayindexoutofbounds/i.test(line)) {
      guards.push({ protectingSymbol: enclosingSymbol, guardType: "bounds-check", evidence: line.trim(), lineNumber: i + 1 });
    }
  }

  return guards;
}

// ─── Baseline vulnerability detection ──────────────────────────────────────────

interface ExtractedVuln {
  lineNumber: number;
  patternType: string;
  severity: string;
  fingerprint: string;
}

function detectBaselineVulns(content: string, filePath: string, language: string): ExtractedVuln[] {
  const vulns: ExtractedVuln[] = [];
  const lines = content.split("\n");

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const lower = line.toLowerCase();

    // SQL injection risk
    if (/string\.format.*select|"select.*\+|'select.*\+/i.test(line) && !/preparedstatement|namedparameter/i.test(lines.slice(Math.max(0, i - 3), i + 4).join("\n"))) {
      addVuln(vulns, filePath, i + 1, "sql-injection-risk", "error");
    }
    // Hardcoded secrets
    if (/(password|secret|api_key|apikey)\s*=\s*["'][^"']{8,}["']/i.test(line) && !/test|mock|example|placeholder/i.test(line)) {
      addVuln(vulns, filePath, i + 1, "hardcoded-secret", "critical");
    }
    // Weak crypto
    if (/md5|sha1(?!ng)|des(?!cription|tination|erialize)/i.test(lower) && /messagedigest|cipher|getinstance/i.test(lower)) {
      addVuln(vulns, filePath, i + 1, "weak-crypto", "warning");
    }
    // System.exit / os._exit
    if (/system\.exit|os\._exit|runtime\.halt/i.test(line)) {
      addVuln(vulns, filePath, i + 1, "abrupt-termination", "warning");
    }
    // Unsafe deserialization
    if (/objectinputstream|readobject|pickle\.load|unsafe.*deserializ/i.test(lower)) {
      addVuln(vulns, filePath, i + 1, "unsafe-deserialization", "error");
    }
  }

  return vulns;
}

function addVuln(vulns: ExtractedVuln[], filePath: string, lineNumber: number, patternType: string, severity: string): void {
  const lineBucket = Math.floor(lineNumber / 10) * 10;
  const fingerprint = `${filePath}|${patternType}|${lineBucket}`;
  if (!vulns.some((v) => v.fingerprint === fingerprint)) {
    vulns.push({ lineNumber, patternType, severity, fingerprint });
  }
}

// ─── AI file summary ──────────────────────────────────────────────────────────

async function aiSummarizeFile(filePath: string, content: string, symbols: ExtractedSymbol[]): Promise<{
  summary: string;
  keyResponsibilities?: string;
  inputsOutputs?: string;
  implicitContracts?: string;
} | null> {
  if (!isAIEnabled()) return null;

  const symbolList = symbols.slice(0, 20)
    .map((s) => `  ${s.type} ${s.name}${s.parentSymbol ? ` (in ${s.parentSymbol})` : ""} L${s.lineStart}`)
    .join("\n");
  const snippet = content.length > 3000 ? content.slice(0, 3000) + "\n... [truncated]" : content;

  try {
    const result = await complete({
      messages: [
        {
          role: "system",
          content: `You are a code analysis engine. Produce a brief JSON summary of the given source file.
Output ONLY a JSON object with keys: "summary" (1-2 sentences), "keyResponsibilities" (bullet points), "inputsOutputs" (main inputs/outputs), "implicitContracts" (hidden assumptions or invariants).
Be precise and technical. Do not include markdown code fences.`,
        },
        {
          role: "user",
          content: `File: ${filePath}\n\nSymbols:\n${symbolList}\n\nCode:\n${snippet}`,
        },
      ],
      temperature: 0.1,
      maxTokens: 500,
    });

    const cleaned = result.content.trim().replace(/^```json\s*/, "").replace(/```$/, "");
    const parsed = JSON.parse(cleaned);
    return {
      summary: String(parsed.summary || ""),
      keyResponsibilities: parsed.keyResponsibilities ? String(parsed.keyResponsibilities) : undefined,
      inputsOutputs: parsed.inputsOutputs ? String(parsed.inputsOutputs) : undefined,
      implicitContracts: parsed.implicitContracts ? String(parsed.implicitContracts) : undefined,
    };
  } catch {
    return null;
  }
}

// ─── File tree enumeration ─────────────────────────────────────────────────────

const BROWSE_CONCURRENCY = 8;

async function enumerateRepoFiles(repoSlug: string, basePath = "", at?: string): Promise<string[]> {
  const allFiles: string[] = [];
  let apiCalls = 0;

  async function walk(dir: string, depth: number) {
    if (depth > MAX_BROWSE_DEPTH) return;
    try {
      const entries = await browseRepo(repoSlug, dir, at);
      apiCalls++;
      if (apiCalls % 20 === 0) {
        console.log(`[RCIE] browse progress: ${apiCalls} API calls, ${allFiles.length} source files found so far`);
      }

      const subDirs: Array<{ fullPath: string; depth: number }> = [];
      for (const entry of entries) {
        const fullPath = dir ? `${dir}/${entry.path.toString}` : entry.path.toString;
        if (entry.type === "FILE") {
          if (detectLanguage(fullPath) || isConfigFile(fullPath)) {
            allFiles.push(fullPath);
          }
        } else if (entry.type === "DIRECTORY") {
          // Skip common non-source directories
          const dirName = entry.path.toString.toLowerCase();
          if (/^(node_modules|\.git|dist|build|target|__pycache__|\.idea|\.vscode|vendor|\.gradle)$/.test(dirName)) continue;
          subDirs.push({ fullPath, depth: depth + 1 });
        }
      }

      // Walk subdirectories concurrently in batches
      for (let i = 0; i < subDirs.length; i += BROWSE_CONCURRENCY) {
        const batch = subDirs.slice(i, i + BROWSE_CONCURRENCY);
        await Promise.all(batch.map((d) => walk(d.fullPath, d.depth)));
      }
    } catch {
      // Access denied or directory gone — skip
    }
  }

  console.log(`[RCIE] starting file enumeration for repo=${repoSlug} basePath="${basePath}"`);
  await walk(basePath, 0);
  console.log(`[RCIE] enumeration done: ${allFiles.length} source files found in ${apiCalls} API calls`);
  return allFiles;
}

// ─── Content hash ──────────────────────────────────────────────────────────────

function contentHash(content: string): string {
  return crypto.createHash("sha256").update(content).digest("hex").slice(0, 16);
}

// ─── Main index function ───────────────────────────────────────────────────────

export interface IndexOptions {
  repoSlug: string;
  commitSha?: string;
  basePath?: string;
  /** If true, clear existing index and re-index from scratch */
  fullReindex?: boolean;
  /** Max number of files to process per run (for incremental) */
  maxFiles?: number;
  /** Enable AI summaries for key files */
  enableAISummaries?: boolean;
}

export interface IndexResult {
  runId: string;
  status: "completed" | "failed";
  filesIndexed: number;
  symbolsExtracted: number;
  dependenciesMapped: number;
  annotationsFound: number;
  guardsDetected: number;
  aiSummariesGenerated: number;
  durationMs: number;
  error?: string;
}

export async function indexRepo(options: IndexOptions): Promise<IndexResult> {
  const {
    repoSlug, commitSha, basePath = "", fullReindex = false,
    maxFiles = 500, enableAISummaries = true,
  } = options;

  const runId = startIndexRun(repoSlug, commitSha);
  const startMs = Date.now();

  let stats = {
    filesIndexed: 0,
    symbolsExtracted: 0,
    dependenciesMapped: 0,
    annotationsFound: 0,
    guardsDetected: 0,
    aiSummariesGenerated: 0,
  };

  try {
    if (fullReindex) {
      clearRepoIndex(repoSlug);
      await clearRepoGraph(repoSlug);
    }

    // 1. Enumerate files
    const filePaths = await enumerateRepoFiles(repoSlug, basePath, commitSha);
    const filesToProcess = filePaths.slice(0, maxFiles);

    // 2. Process each file
    const codeFileInputs: UpsertCodeFileInput[] = [];
    const allSymbolInputs: { filePath: string; symbols: InsertSymbolInput[] }[] = [];
    const allDepInputs: { filePath: string; deps: InsertDependencyInput[] }[] = [];
    const allAnnotationInputs: { filePath: string; annotations: InsertAnnotationInput[] }[] = [];
    const allGuardInputs: { filePath: string; guards: InsertGuardInput[] }[] = [];
    const allVulnInputs: UpsertBaselineVulnInput[] = [];
    const allGraphNodes: GraphNodeInput[] = [];
    const allGraphEdges: GraphEdgeInput[] = [];
    const aiCandidates: Array<{ filePath: string; content: string; symbols: ExtractedSymbol[] }> = [];

    let processedCount = 0;
    for (const filePath of filesToProcess) {
      const language = detectLanguage(filePath);
      if (!language) continue;

      processedCount++;
      if (processedCount % 25 === 0) {
        console.log(`[RCIE] processing file ${processedCount}/${filesToProcess.length}: ${stats.filesIndexed} indexed, ${stats.symbolsExtracted} symbols`);
      }

      // Check if already indexed with same content hash (incremental)
      let content: string;
      try {
        content = await getFileContent(repoSlug, filePath, commitSha);
      } catch {
        continue; // File may have been deleted
      }

      const hash = contentHash(content);
      if (!fullReindex) {
        const existing = getCodeFile(repoSlug, filePath);
        if (existing && existing.contentHash === hash) continue;
      }

      const lines = content.split("\n");
      if (lines.length > MAX_FILE_LINES) continue;

      const isTest = isTestFilePath(filePath);
      const isGen = isGeneratedFile(filePath, content);
      const isInfra = isInfraConfig(filePath);

      // File record
      codeFileInputs.push({
        filePath,
        commitSha: commitSha || "HEAD",
        language,
        lineCount: lines.length,
        subsystem: classifySubsystem(filePath),
        sensitivity: detectSensitivity(filePath, content),
        isGenerated: isGen,
        isInfraConfig: isInfra,
        isTest,
        contentHash: hash,
      });

      // Clear previous index data for this file
      clearFileIndex(repoSlug, filePath);
      await clearFileGraph(repoSlug, filePath);

      // Extract symbols
      const symbols = extractSymbols(content, language, filePath);
      const symbolInputs: InsertSymbolInput[] = symbols.map((s) => ({
        filePath,
        symbolName: s.name,
        symbolType: s.type,
        visibility: s.visibility,
        isStatic: s.isStatic,
        isAbstract: s.isAbstract,
        lineStart: s.lineStart,
        lineEnd: s.lineEnd,
        parentSymbol: s.parentSymbol,
        signature: s.signature,
        returnType: s.returnType,
        parameterTypes: s.parameterTypes,
      }));
      allSymbolInputs.push({ filePath, symbols: symbolInputs });
      stats.symbolsExtracted += symbols.length;

      // Extract dependencies
      const deps = extractDependencies(content, language, filePath);
      const depInputs: InsertDependencyInput[] = deps.map((d) => ({
        sourceFile: filePath,
        sourceSymbol: d.sourceSymbol,
        targetFile: d.targetFile,
        targetSymbol: d.targetSymbol,
        dependencyType: d.dependencyType,
        isDirect: true,
        metadata: d.metadata,
      }));
      allDepInputs.push({ filePath, deps: depInputs });
      stats.dependenciesMapped += deps.length;

      // Extract annotations
      const annotations = extractAnnotations(content, language, symbols);
      const annotationInputs: InsertAnnotationInput[] = annotations.map((a) => ({
        filePath,
        targetSymbol: a.targetSymbol,
        annotationName: a.annotationName,
        annotationParams: a.annotationParams,
        classification: a.classification,
        lineNumber: a.lineNumber,
      }));
      allAnnotationInputs.push({ filePath, annotations: annotationInputs });
      stats.annotationsFound += annotations.length;

      // Extract guards
      const guards = extractGuards(content, language, symbols);
      const guardInputs: InsertGuardInput[] = guards.map((g) => ({
        filePath,
        protectingSymbol: g.protectingSymbol,
        guardType: g.guardType,
        scope: g.scope,
        evidence: g.evidence,
        lineNumber: g.lineNumber,
      }));
      allGuardInputs.push({ filePath, guards: guardInputs });
      stats.guardsDetected += guards.length;

      // Detect baseline vulnerabilities
      const vulns = detectBaselineVulns(content, filePath, language);
      for (const v of vulns) {
        allVulnInputs.push({
          filePath,
          lineNumber: v.lineNumber,
          patternType: v.patternType,
          severity: v.severity,
          fingerprint: v.fingerprint,
        });
      }

      const graph = buildGraphWarehouseForFile({
        repoSlug,
        filePath,
        content,
        symbols,
        dependencies: deps,
        annotations,
        subsystem: classifySubsystem(filePath),
      });
      allGraphNodes.push(...graph.nodes);
      allGraphEdges.push(...graph.edges);

      // AI summary candidate
      if (enableAISummaries && !isGen && !isTest && symbols.length > 0 && aiCandidates.length < MAX_AI_SUMMARY_FILES) {
        aiCandidates.push({ filePath, content, symbols });
      }

      stats.filesIndexed++;
    }

    // 2b. Process config files for bean-wiring dependencies
    const configFiles = filePaths.filter((fp) => isConfigFile(fp));
    for (const cfgPath of configFiles.slice(0, 50)) {
      let cfgContent: string;
      try {
        cfgContent = await getFileContent(repoSlug, cfgPath, commitSha);
      } catch {
        continue;
      }
      const cfgDeps = extractConfigDependencies(cfgContent, cfgPath);
      if (cfgDeps.length > 0) {
        const depInputs: InsertDependencyInput[] = cfgDeps.map((d) => ({
          sourceFile: cfgPath,
          sourceSymbol: d.sourceSymbol,
          targetFile: d.targetFile,
          targetSymbol: d.targetSymbol,
          dependencyType: d.dependencyType,
          isDirect: true,
          metadata: d.metadata,
        }));
        allDepInputs.push({ filePath: cfgPath, deps: depInputs });
        stats.dependenciesMapped += cfgDeps.length;
      }
    }

    // 3. Bulk write to DB
    upsertCodeFiles(repoSlug, codeFileInputs);
    for (const { symbols } of allSymbolInputs) insertSymbols(repoSlug, symbols);
    for (const { deps } of allDepInputs) insertDependencies(repoSlug, deps);
    for (const { annotations } of allAnnotationInputs) insertAnnotations(repoSlug, annotations);
    for (const { guards } of allGuardInputs) insertGuards(repoSlug, guards);
    upsertBaselineVulns(repoSlug, allVulnInputs);
    await upsertGraphNodes(repoSlug, allGraphNodes);
    await upsertGraphEdges(repoSlug, allGraphEdges);

    // 4. AI summaries (sequential to avoid overwhelming provider)
    if (enableAISummaries && isAIEnabled()) {
      const summaryInputs: UpsertAISummaryInput[] = [];
      const providerInfo = getProviderInfo();

      for (const candidate of aiCandidates) {
        const aiResult = await aiSummarizeFile(candidate.filePath, candidate.content, candidate.symbols);
        if (aiResult) {
          summaryInputs.push({
            filePath: candidate.filePath,
            summary: aiResult.summary,
            keyResponsibilities: aiResult.keyResponsibilities,
            inputsOutputs: aiResult.inputsOutputs,
            implicitContracts: aiResult.implicitContracts,
            contentHash: contentHash(candidate.content),
            provider: providerInfo.provider,
            model: providerInfo.model,
          });
          stats.aiSummariesGenerated++;
        }
      }

      upsertAISummaries(repoSlug, summaryInputs);
    }

    const durationMs = Date.now() - startMs;
    completeIndexRun(runId, { ...stats, durationMs });

    return {
      runId,
      status: "completed",
      ...stats,
      durationMs,
    };
  } catch (err: any) {
    const durationMs = Date.now() - startMs;
    const errorMsg = err?.message || String(err);
    failIndexRun(runId, errorMsg);
    return {
      runId,
      status: "failed",
      ...stats,
      durationMs,
      error: errorMsg,
    };
  }
}
