// ──────────────────────────────────────────────────────────────
// Mock Jira Adapter
// Provides realistic demo data for development and testing.
// ──────────────────────────────────────────────────────────────

import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import type { IJiraAdapter, SyncOptions, SyncResult } from './adapter.interface';

@Injectable()
export class JiraMockAdapter implements IJiraAdapter {
  private readonly logger = new Logger(JiraMockAdapter.name);

  constructor(private readonly prisma: PrismaService) {}

  async testConnection(): Promise<boolean> {
    this.logger.log('Mock Jira: connection OK');
    return true;
  }

  async syncProjects(): Promise<SyncResult> {
    this.logger.log('Mock Jira: syncing projects');
    const projects = [
      { key: 'ACI', name: 'ACI Payments Platform', externalId: 'proj-aci' },
      { key: 'PAY', name: 'Payment Gateway', externalId: 'proj-pay' },
      { key: 'INF', name: 'Infrastructure', externalId: 'proj-inf' },
    ];

    for (const p of projects) {
      await this.prisma.project.upsert({
        where: { key: p.key },
        update: { name: p.name },
        create: { key: p.key, name: p.name, externalId: p.externalId },
      });
    }

    return { itemsSynced: projects.length, errors: [], hasMore: false };
  }

  async syncSprints(projectKey: string): Promise<SyncResult> {
    this.logger.log(`Mock Jira: syncing sprints for ${projectKey}`);
    const project = await this.prisma.project.findUnique({ where: { key: projectKey } });
    if (!project) return { itemsSynced: 0, errors: [`Project ${projectKey} not found`], hasMore: false };

    const sprints = [
      { name: 'Sprint 23', state: 'CLOSED', startDate: new Date('2026-02-17'), endDate: new Date('2026-02-28') },
      { name: 'Sprint 24', state: 'ACTIVE', startDate: new Date('2026-03-03'), endDate: new Date('2026-03-14') },
      { name: 'Sprint 25', state: 'FUTURE', startDate: new Date('2026-03-17'), endDate: new Date('2026-03-28') },
    ];

    for (const s of sprints) {
      const extId = `${projectKey}-${s.name.replace(/\s/g, '-').toLowerCase()}`;
      await this.prisma.sprint.upsert({
        where: { id: extId },
        update: { state: s.state },
        create: {
          id: extId,
          projectId: project.id,
          externalId: extId,
          name: s.name,
          state: s.state,
          startDate: s.startDate,
          endDate: s.endDate,
        },
      });
    }

    return { itemsSynced: sprints.length, errors: [], hasMore: false };
  }

  async syncIssues(_options: SyncOptions): Promise<SyncResult> {
    this.logger.log('Mock Jira: syncing issues (demo data created via seed)');
    // Real issue data is generated by the seed script rather than this adapter,
    // so the mock adapter is a no-op for issues after initial seeding.
    return { itemsSynced: 0, errors: [], hasMore: false };
  }
}
