// ─────────────────────────────────────────────────────────────
// Story Readiness — Jira Payload Builder (Dry-Run / Preview)
// ─────────────────────────────────────────────────────────────
import type {
  StoryReadinessSnapshot,
  JiraWriteBackPayload,
  JiraSubtaskPayload,
  ClarificationQuestion,
  SuggestedSubtask,
} from "./types";

// ── Comment Formatter ──────────────────────────────────────

function formatReadinessComment(snapshot: StoryReadinessSnapshot): string {
  const lines: string[] = [];

  // Header
  lines.push(`h3. 📊 Story Readiness Report`);
  lines.push(`||Field||Value||`);
  lines.push(`|Story|${snapshot.jiraKey}|`);
  lines.push(`|Type|${snapshot.storyType}|`);
  lines.push(`|Readiness|*${snapshot.readinessState}* (${snapshot.readinessScoreOverall}/100)|`);
  lines.push(`|Knowledge Confidence|${snapshot.knowledgeConfidence}|`);
  lines.push(`|Generated|${new Date(snapshot.generatedAt).toLocaleString()}|`);
  lines.push("");

  // Dimension Breakdown
  lines.push(`h4. Readiness Dimensions`);
  lines.push(`||Dimension||Score||Confidence||`);
  for (const dim of snapshot.readinessDimensions) {
    const bar = dim.score >= 70 ? "(/)" : dim.score >= 40 ? "(!)" : "(x)";
    lines.push(`|${dim.name}|${bar} ${dim.score}/100|${dim.confidence}|`);
  }
  lines.push("");

  // Blocking Gaps
  if (snapshot.blockingGaps.length > 0) {
    lines.push(`h4. {color:red}Blocking Gaps{color}`);
    for (const gap of snapshot.blockingGaps) {
      lines.push(`* (!) *${gap.severity.toUpperCase()}*: ${gap.description}`);
    }
    lines.push("");
  }

  // Clarification Questions
  if (snapshot.clarificationQuestions.length > 0) {
    lines.push(`h4. Clarification Questions`);
    const blockers = snapshot.clarificationQuestions.filter((q) => q.severity === "blocker");
    const important = snapshot.clarificationQuestions.filter((q) => q.severity === "important");
    const optional = snapshot.clarificationQuestions.filter((q) => q.severity === "optional");

    if (blockers.length > 0) {
      lines.push(`*Blockers:*`);
      for (const q of blockers) {
        lines.push(`# {color:red}[${q.category}]{color} ${q.questionText}`);
        lines.push(`** _Why:_ ${q.whyThisMatters}`);
      }
    }
    if (important.length > 0) {
      lines.push(`*Important:*`);
      for (const q of important) {
        lines.push(`# [${q.category}] ${q.questionText}`);
        lines.push(`** _Why:_ ${q.whyThisMatters}`);
      }
    }
    if (optional.length > 0) {
      lines.push(`*Optional:*`);
      for (const q of optional) {
        lines.push(`# [${q.category}] ${q.questionText}`);
      }
    }
    lines.push("");
  }

  // Suggested subtasks summary
  if (snapshot.suggestedSubtasks.length > 0) {
    lines.push(`h4. Suggested Subtasks (${snapshot.suggestedSubtasks.length})`);
    for (const st of snapshot.suggestedSubtasks) {
      const draft = st.isDraft ? " _(draft)_" : "";
      lines.push(`# [${st.category}] ${st.title}${draft}`);
    }
    lines.push("");
  }

  lines.push(`----`);
  lines.push(`_Generated by GroomPilot Story Readiness Copilot v${snapshot.version}_`);

  return lines.join("\n");
}

// ── Subtask Payload Builder ────────────────────────────────

function buildSubtaskPayloads(
  snapshot: StoryReadinessSnapshot,
  selectedSubtaskIds?: string[],
): JiraSubtaskPayload[] {
  let subtasks: SuggestedSubtask[];

  if (selectedSubtaskIds && selectedSubtaskIds.length > 0) {
    const idSet = new Set(selectedSubtaskIds);
    subtasks = snapshot.suggestedSubtasks.filter((st) => idSet.has(st.id));
  } else {
    // Default: include non-draft subtasks
    subtasks = snapshot.suggestedSubtasks.filter((st) => !st.isDraft);
  }

  return subtasks.map((st) => ({
    summary: st.title,
    description: [
      st.description,
      "",
      `*Why:* ${st.whyNeeded}`,
      st.dependencyHints.length > 0
        ? `*Dependencies:* ${st.dependencyHints.join(", ")}`
        : "",
      `*Category:* ${st.category}`,
      `*Confidence:* ${st.confidence}`,
    ]
      .filter(Boolean)
      .join("\n"),
    labels: ["groompilot-generated", `readiness-${snapshot.storyType.toLowerCase()}`],
  }));
}

// ── Public API ─────────────────────────────────────────────

/**
 * Builds a Jira write-back payload in preview (dry-run) mode.
 * Does NOT interact with Jira.
 */
export function buildJiraPayload(
  snapshot: StoryReadinessSnapshot,
  options?: {
    includeComment?: boolean;
    includeSubtasks?: boolean;
    selectedSubtaskIds?: string[];
    dryRun?: boolean;
  },
): JiraWriteBackPayload {
  const opts = {
    includeComment: true,
    includeSubtasks: true,
    dryRun: true,  // always dry-run in phase 1
    ...options,
  };

  return {
    jiraKey: snapshot.jiraKey,
    commentBody: opts.includeComment ? formatReadinessComment(snapshot) : "",
    subtaskPayloads: opts.includeSubtasks
      ? buildSubtaskPayloads(snapshot, opts.selectedSubtaskIds)
      : [],
    dryRun: opts.dryRun,
  };
}
