CREATE TABLE IF NOT EXISTS team_members (
  id TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  bitbucket_name TEXT,
  organisation TEXT NOT NULL DEFAULT 'aciworldwide',
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

INSERT OR IGNORE INTO team_members (id, display_name, email, bitbucket_name, organisation) VALUES
  ('tm-001', 'Narendra Kumar', 'narendra.kumar@peerislands.io', 'Narendra Kumar', 'peerislands'),
  ('tm-002', 'Kumaran Venkataraman', 'kumaran.venkataraman@aciworldwide.com', 'Kumaran Venkataraman', 'aciworldwide'),
  ('tm-003', 'Nithya Masanapothydurai', 'nithya.masanapothydurai@aciworldwide.com', 'Nithya Masanapothydurai', 'aciworldwide'),
  ('tm-004', 'Vikeshkumar Gupta', 'vikeshkumar.gupta@aciworldwide.com', 'Vikeshkumar Gupta', 'aciworldwide'),
  ('tm-005', 'Akshay Kumar', 'akshay.kumar@aciworldwide.com', 'Akshay Kumar', 'aciworldwide'),
  ('tm-006', 'Vidyasagar Yedireswarapu', 'vidyasagar.yedireswarapu@aciworldwide.com', 'Vidyasagar Yedireswarapu', 'aciworldwide'),
  ('tm-007', 'Meenakshi Gupta', 'meenakshi.gupta@aciworldwide.com', 'Meenakshi Gupta', 'aciworldwide'),
  ('tm-008', 'Ashiskumar Parida', 'ashiskumar.parida@aciworldwide.com', 'Ashiskumar Parida', 'aciworldwide'),
  ('tm-009', 'Deep Narayan Kumar', 'deepnarayan.kumar@aciworldwide.com', 'Deep Narayan Kumar', 'aciworldwide'),
  ('tm-010', 'Gulshan Kumar', 'gulshan.kumar@aciworldwide.com', 'Gulshan Kumar', 'aciworldwide'),
  ('tm-011', 'Raghul Selvam', 'raghul.selvam@aciworldwide.com', 'Raghul Selvam', 'aciworldwide'),
  ('tm-012', 'Onkar Mishra', 'onkar.mishra@peerislands.io', 'Onkar Mishra', 'peerislands'),
  ('tm-013', 'Supriya Bagade', 'supriya.bagade@aciworldwide.com', 'Supriya Bagade', 'aciworldwide'),
  ('tm-014', 'Rajani Subramanyam', 'rajani.subramanyam@aciworldwide.com', 'Rajani Subramanyam', 'aciworldwide'),
  ('tm-015', 'Akash Patel', 'akash.d.patel@aciworldwide.com', 'Akash Patel', 'aciworldwide'),
  ('tm-016', 'AhilSnekaPriya Balakrishnan', 'ahilsnekapriya.balakrishnan@aciworldwide.com', 'AhilSnekaPriya Balakrishnan', 'aciworldwide'),
  ('tm-017', 'Ajay Gaikwad', 'ajay.gaikwad@aciworldwide.com', 'Ajay Gaikwad', 'aciworldwide'),
  ('tm-018', 'Ritesh Khadgaray', 'ritesh.khadgaray@aciworldwide.com', 'Ritesh Khadgaray', 'aciworldwide'),
  ('tm-019', 'Gowtham Vepuri', 'gowtham.vepuri@aciworldwide.com', 'Gowtham Vepuri', 'aciworldwide'),
  ('tm-020', 'Sneha Mishra', 'sneha.mishra@aciworldwide.com', 'Sneha Mishra', 'aciworldwide'),
  ('tm-021', 'Rajesh Kanagaraju', 'rajesh.kanagaraju@aciworldwide.com', 'Rajesh Kanagaraju', 'aciworldwide'),
  ('tm-022', 'Gokul Prashanth', 'gokul.prashanth@aciworldwide.com', 'Gokul Prashanth', 'aciworldwide'),
  ('tm-023', 'Prateek Jain', 'prateek.jain@aciworldwide.com', 'Prateek Jain', 'aciworldwide'),
  ('tm-024', 'Ketan Pande', 'ketan.pande@aciworldwide.com', 'Ketan Pande', 'aciworldwide'),
  ('tm-025', 'Nagadarshan AH', 'nagadarshan.ah@aciworldwide.com', 'Nagadarshan AH', 'aciworldwide'),
  ('tm-026', 'Preethi Muruganantham', 'preethi.muruganantham@aciworldwide.com', 'Preethi Muruganantham', 'aciworldwide'),
  ('tm-027', 'Prince Allwin', 'prince.allwin@aciworldwide.com', 'Prince Allwin', 'aciworldwide'),
  ('tm-028', 'Vandana Singh', 'vandana.singh@aciworldwide.com', 'Vandana Singh', 'aciworldwide'),
  ('tm-029', 'Sreekanth S', 'sreekanth.s@aciworldwide.com', 'Sreekanth S', 'aciworldwide'),
  ('tm-030', 'Kithiyons Irudhayaraj', 'kithiyons.irudhayaraj@aciworldwide.com', 'Kithiyons Irudhayaraj', 'aciworldwide'),
  ('tm-031', 'Santhoshkumar Anbalagan', 'santhoshkumar.anbalagan@aciworldwide.com', 'Santhoshkumar Anbalagan', 'aciworldwide'),
  ('tm-032', 'Hariprasad Perupurayil', 'hariprasad.perupurayil@peerislands.io', 'Hariprasad Perupurayil', 'peerislands');
